### ISSUE TITLE
Accessing the Docker API [security] 

### ISSUE THREAD

**Issue by rizerzero** [crazy-max/docker-n8n#1]
Hi, Thank you for the great work you're doing, 

I noticed that when you are using Traefik you are using the docker socket directly which is raising a security problem, 
some people use docker_socket_proxy  as a solution to this, and some are trying to use podman, I'm not sure what's best but it would improve the security of the projects to avoid mounting the docket socket into Traefik. 

Thanks

**Comment by crazy-max** [comment]
@rizerzero Yes sure feel free to do so that's just an example based on Traefik prereq :) I was thinking creating my own docker proxy someday maybe a future project :eyes: [docker-socket-proxy](https://github.com/Tecnativa/docker-socket-proxy) looks good to me.
